Fix Date Picker Issue Using @nextui-org/react in Next.js
mowblox/truecast pull request #66
Opened 2024-10-09 12:55 UTC by Ratawine7

I resolved an issue with the date picker by integrating the @nextui-org/react library.
Improved date selection functionality and ensured compatibility with the project.
The updated date picker provides better UI/UX and cross-browser support.
@mikehammond

2024-10-10 20:35 UTC, mikehammond requested changes

2024-10-10 20:35 UTC, mikehammond commented on frontend/src/components/elections/CreateElection.tsx
> +import { DatePicker } from "@nextui-org/react";
@Ratawine7 The package you are importing has not even been installed as a dependency.
I am checking the `frontend/package.json` file and it is not part of the list of deps.

2024-10-11 12:58 UTC, Ratawine7 commented
Hi, Michael
sorry I did not mention this; you have to install @netui-org/react as a
global package
then import the datepicker library.
thanks

2024-10-14 05:45 UTC, mikehammond commented
@Ratawine7 Did you follow the guide [here](https://nextui.org/docs/guide/installation#install-packages) to install and setup?

2025-01-04 00:43 UTC, mikehammond approved these changes

2025-01-04 00:45 UTC, closed without merging